/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
//note: for Email, IP address and LinkedIN try entering full details to enable the save button
/**
 *
 * @author Kiran
 */
import java.awt.Image;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private BufferedImage Image1;
    User user;
    public CreateJPanel(User user) {
        initComponents();
        this.user = user;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        gd = new javax.swing.JTextField();
        tn = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        vpn = new javax.swing.JTextField();
        ui = new javax.swing.JTextField();
        ban = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        mrn = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        hbn = new javax.swing.JTextField();
        ipa = new javax.swing.JTextField();
        ea = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTN = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();
        jLabelbs = new javax.swing.JLabel();
        jLabelhbn = new javax.swing.JLabel();
        jLabelpn = new javax.swing.JLabel();
        jLabelcn = new javax.swing.JLabel();
        jLabelpa = new javax.swing.JLabel();
        jLabelln = new javax.swing.JLabel();
        jLabelea = new javax.swing.JLabel();
        jLabelui = new javax.swing.JLabel();
        jLableN = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabelM = new javax.swing.JLabel();
        jLabelssn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        name.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nameInputMethodTextChanged(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });

        gd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdActionPerformed(evt);
            }
        });
        gd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gdKeyReleased(evt);
            }
        });

        tn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnKeyReleased(evt);
            }
        });

        jButtonBrowse.setBackground(new java.awt.Color(255, 204, 204));
        jButtonBrowse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonBrowse.setText("Browse Photo");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jLabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });

        vpn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vpnKeyReleased(evt);
            }
        });

        ui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uiKeyReleased(evt);
            }
        });

        ban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                banKeyReleased(evt);
            }
        });

        ssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ssnKeyReleased(evt);
            }
        });

        mrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrnActionPerformed(evt);
            }
        });
        mrn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mrnKeyReleased(evt);
            }
        });

        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
        });

        hbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hbnKeyReleased(evt);
            }
        });

        ipa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipaKeyReleased(evt);
            }
        });

        ea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eaKeyReleased(evt);
            }
        });

        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Country");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Telephone Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Date of Birth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Helath plan beneficiary Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Certificate Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("BankAccount Number");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("LinkedIn");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Vehicle License plate number");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Unique Identifier");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Email Address");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel16.setText("Medical Record Number");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Internet Protocol Address");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("Fax number");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("Social Security Number");

        jLabelTN.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelTN.setForeground(new java.awt.Color(255, 51, 51));

        jLabelG.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelG.setForeground(new java.awt.Color(255, 51, 51));

        jLabelF.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelF.setForeground(new java.awt.Color(255, 0, 0));

        jLabelbs.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelbs.setForeground(new java.awt.Color(255, 0, 0));

        jLabelhbn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelhbn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelpn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelpn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelcn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelcn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelpa.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelpa.setForeground(new java.awt.Color(255, 51, 51));

        jLabelln.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelln.setForeground(new java.awt.Color(255, 0, 0));

        jLabelea.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelea.setForeground(new java.awt.Color(255, 0, 0));

        jLabelui.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelui.setForeground(new java.awt.Color(255, 0, 0));

        jLableN.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLableN.setForeground(new java.awt.Color(255, 0, 51));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("   CREATE PROFILE");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(403, 403, 403)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1)))
                                        .addGap(5, 5, 5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jButtonBrowse)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel24)
                                                            .addComponent(jLabel4))
                                                        .addGap(8, 8, 8)))
                                                .addComponent(jLabel16)))))))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ssn)
                            .addComponent(mrn)
                            .addComponent(hbn)
                            .addComponent(cn)
                            .addComponent(vpn)
                            .addComponent(ln)
                            .addComponent(ipa)
                            .addComponent(ui)
                            .addComponent(ea)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ban, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabelea)
                            .addComponent(jLabelui)
                            .addComponent(jLabelpa)
                            .addComponent(jLabelln)
                            .addComponent(jLabelpn)
                            .addComponent(jLabelcn)
                            .addComponent(jLabelhbn)
                            .addComponent(jLabelF)
                            .addComponent(jLabelTN)
                            .addComponent(jLabelG)
                            .addComponent(jLableN)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelbs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelM)))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelssn)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel1)))
                            .addComponent(jLableN, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 649, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelG)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelea))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel24))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabelF)
                                                        .addGap(3, 3, 3)
                                                        .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabelssn))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(mrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(hbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelpn))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelcn))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel9)
                                                            .addComponent(vpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel8)
                                                            .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(79, 79, 79)
                                                        .addComponent(jLabelln)))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel14)
                                                    .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelui))))
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelpa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jButtonBrowse))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelhbn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTN)
                                    .addComponent(jLabel3))
                                .addGap(177, 177, 177)
                                .addComponent(jLabelbs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 109, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 108, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
//Checking input pattern for name text field
    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{0,30}$";//pattern for name text field         
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(name.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLableN.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLableN.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_nameKeyReleased

    private void gdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_gdActionPerformed
////Checking input pattern for geographic data text field
    private void gdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gdKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{0,30}$";//pattern for geographic data  text field         
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(gd.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelG.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelG.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_gdKeyReleased
//Checking input pattern for telephone number text field 
    private void tnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{10}$";//pattern for telephone number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(tn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelTN.setText("Enter 10 digit phone number!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelTN.setText(null);
            jButton3.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_tnKeyReleased
//Action performed on browse photo button    
    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
        this.Image1 = null;
        JFileChooser browseImageFile = new JFileChooser();//filechooser obhject created to browse the image file
        //browseImageFile.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        
        FileNameExtensionFilter fnef =  new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");//file onject created to add extension of the image file
        browseImageFile.addChoosableFileFilter(fnef);//choose amongst the filter
        
        //int showOpenDialogue = browseImageFile.showOpenDialog(null);
        //int DialogueState = browseImageFile.showSaveDialog(this);
        int showOpenDialogue = browseImageFile.showSaveDialog(null);//open window to browse image
        
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            
            File selectedImageFile = browseImageFile.getSelectedFile();//Object created to store the image
            //String selectedImagePath = selectedImageFile.getAbsolutePath();//object created to store the absolute path of the image

            //JOptionPane.showMessageDialog(null, selectedImagePath);// window that shows the absolute path of the selected image
            
//            jLabelImage.setIcon(resizePic(path));
            try {
                this.Image1 = ImageIO.read(selectedImageFile);
                ImageIcon ii = new ImageIcon(Image1);//ImageIcon object for selected Image 
                Image image  = ii.getImage().getScaledInstance(jLabelImage.getWidth(),jLabelImage.getHeight(), Image.SCALE_SMOOTH);//adding width height to the image
                jLabelImage.setIcon(new ImageIcon(image));//setting the selected image to the label for display
            } catch (IOException ex){
                JOptionPane.showMessageDialog(this, "Image is not uploaded");
            }
            
            
            
            
        }
        
    }//GEN-LAST:event_jButtonBrowseActionPerformed
//Checking input pattern for Fax Number text field 
    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{10}$";//pattern for Fax Number field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(fn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelF.setText("Enter 10 digit Fax number!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelF.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_fnKeyReleased
//Checking input pattern for Vehicle Plate Number text field 
    private void vpnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vpnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,15}$";//pattern for Vehicle Plate Number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(vpn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelpn.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelpn.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_vpnKeyReleased
//Checking input pattern for Unique Identifier text field 
    private void uiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uiKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,15}$";//pattern for Unique Identifier text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ui.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelui.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelui.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_uiKeyReleased
//Checking input pattern for Bank Account Number text field 
    private void banKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_banKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{9}$";//pattern for Bank Account Number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ban.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelbs.setText("Oops!!Enter 9 digit bank number");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelbs.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_banKeyReleased
//Checking input pattern for Social Security Number text field 
    private void ssnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{9}$";//pattern for Social Security number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ssn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelssn.setText("Enter 9 digit SSN!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelssn.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_ssnKeyReleased

    private void mrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrnActionPerformed
//Checking input pattern for Medical Record Number text field 
    private void mrnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mrnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,15}$";//pattern for Medical Record Number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(mrn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelM.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelM.setText(null);
            jButton3.setEnabled(true);
        }

    }//GEN-LAST:event_mrnKeyReleased
//Checking input pattern for Certificate Number text field 
    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,15}$";//pattern for Certificate Number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(cn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelcn.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelcn.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_cnKeyReleased
//Checking input pattern for Health Beneficiary Number text field 
    private void hbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hbnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,15}$";//pattern for Health Beneficiary Number text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(hbn.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelhbn.setText("Something went wrong!!");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelhbn.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_hbnKeyReleased
//Checking input pattern for Internet Protocol Address text field 
    private void ipaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipaKeyReleased
        // TODO add your handling code here:
        String PATTERN="^\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b$";//pattern for Internet Protocol Address text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ipa.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelpa.setText("Oops!! Try entering full IP address.");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelpa.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_ipaKeyReleased
//Checking input pattern for Email Address text field 
    private void eaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eaKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";//pattern for Email Address text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ea.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelea.setText("Oops!! Try entering full email address.");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelea.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_eaKeyReleased
//Checking input pattern for LinkedIn text field //pattern for LinkedIn text field
    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
        // TODO add your handling code here:
        String PATTERN="^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$";//pattern for LinkedIn text field
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(ln.getText());
        if(!match.matches()){ //if pattern does't match display below message and disable save button 
            jLabelln.setText("Oops!! Try something like https://linkedin.com");
            jButton3.setEnabled(false);
        }
        else{ //if pattern matches do not display any message and enable the save button
            jLabelln.setText(null);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_lnKeyReleased
//Saving all the input text field variables in declared variables of Java class using Set method
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(this.Image1 == null){
            JOptionPane.showMessageDialog(this, "Please add image", "Image is mandatory", JOptionPane.ERROR_MESSAGE);
            return;
        }
        savetoUser();
        
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void savetoUser(){
        user.setName(name.getText());
        user.setGeographicData(gd.getText());
        long telno = Integer.parseInt(tn.getText().trim());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setTelephoneNumber(telno);
        long faxno = Integer.parseInt(fn.getText().trim());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setFaxNumber(faxno);
        user.setEmailAddress(ea.getText());
        long ssnum = Integer.parseInt(ssn.getText().trim());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setSsn(ssnum);
        user.setMedicalRecordNumber(mrn.getText());
        user.setHealthPlanBeneficiary(hbn.getText());
        long banu = Integer.parseInt(ban.getText());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setBankAccountNumbers(banu);
        long cnum = Integer.parseInt(cn.getText().trim());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setLicenseNumber(cnum);
        user.setLicensePlates(vpn.getText().trim());
        user.setLinkedIn(ln.getText());
        long uid = Integer.parseInt(ui.getText().trim());//Converting from string to Integer since input text bydefault gives string and variable to be stored is in integer format
        user.setUniqueIdentifier(uid);
        user.setInternetProtocolAddress(ipa.getText().trim());
        user.setDateOfBirth(jDateChooser1.getDate());
        user.setImage(jLabelImage.getIcon());
        
        JOptionPane.showMessageDialog(this, "User information saved!");
    }
    private void nameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ban;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField ea;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField gd;
    private javax.swing.JTextField hbn;
    private javax.swing.JTextField ipa;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBrowse;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelG;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelTN;
    private javax.swing.JLabel jLabelbs;
    private javax.swing.JLabel jLabelcn;
    private javax.swing.JLabel jLabelea;
    private javax.swing.JLabel jLabelhbn;
    private javax.swing.JLabel jLabelln;
    private javax.swing.JLabel jLabelpa;
    private javax.swing.JLabel jLabelpn;
    private javax.swing.JLabel jLabelssn;
    private javax.swing.JLabel jLabelui;
    private javax.swing.JLabel jLableN;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mrn;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField ui;
    private javax.swing.JTextField vpn;
    // End of variables declaration//GEN-END:variables
}
