/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.toedter.calendar.JDateChooser;
import javax.swing.ImageIcon;
import model.User;

/**
 *
 * @author Kiran
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    User user;
    public ViewJPanel(User user) {
        initComponents();
        this.user = user;
        viewUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTN = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();
        jLabelssn = new javax.swing.JLabel();
        jLabelM = new javax.swing.JLabel();
        jLabelbs = new javax.swing.JLabel();
        jLabelhbn = new javax.swing.JLabel();
        jLabelpn = new javax.swing.JLabel();
        jLabelcn = new javax.swing.JLabel();
        jLabelpa = new javax.swing.JLabel();
        jLabelln = new javax.swing.JLabel();
        jLabelea = new javax.swing.JLabel();
        jLabelui = new javax.swing.JLabel();
        jLableN = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gd = new javax.swing.JTextField();
        tn = new javax.swing.JTextField();
        jDateChooser1 = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        mrn = new javax.swing.JTextField();
        hbn = new javax.swing.JTextField();
        bn = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        vpn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        ipa = new javax.swing.JTextField();
        ui = new javax.swing.JTextField();
        ea = new javax.swing.JTextField();

        jLabel1.setText("Name");

        jLabel2.setText("Geographic data");

        jLabel3.setText("Telephone Number");

        jLabel4.setText("Date of Birth");

        jLabel5.setText("Helath plan beneficiary Number");

        jLabel6.setText("Certificate Number");

        jLabel7.setText("BankAccount Number");

        jLabel8.setText("LinkedIn");

        jLabel9.setText("Vehicle License plate number");

        jLabel14.setText("Unique Identifier");

        jLabel15.setText("Email Address");

        jLabel16.setText("Medical Record Number");

        jLabel17.setText("Internet Protocol Address");

        jLabel24.setText("Fax number");

        jLabel25.setText("Social Security Number");

        jLabelTN.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelTN.setForeground(new java.awt.Color(255, 51, 51));

        jLabelG.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelG.setForeground(new java.awt.Color(255, 51, 51));

        jLabelF.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelF.setForeground(new java.awt.Color(255, 0, 0));

        jLabelssn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelssn.setForeground(new java.awt.Color(255, 0, 51));

        jLabelM.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelM.setForeground(new java.awt.Color(255, 0, 0));

        jLabelbs.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelbs.setForeground(new java.awt.Color(255, 0, 0));

        jLabelhbn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelhbn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelpn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelpn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelcn.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelcn.setForeground(new java.awt.Color(255, 0, 0));

        jLabelpa.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelpa.setForeground(new java.awt.Color(255, 51, 51));

        jLabelln.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelln.setForeground(new java.awt.Color(255, 0, 0));

        jLabelea.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelea.setForeground(new java.awt.Color(255, 0, 0));

        jLabelui.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabelui.setForeground(new java.awt.Color(255, 0, 0));

        jLableN.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLableN.setForeground(new java.awt.Color(255, 0, 51));

        name.setText("jTextField1");

        gd.setText("jTextField1");

        tn.setText("jTextField1");

        jDateChooser1.setText("jTextField1");

        fn.setText("jTextField1");

        ssn.setText("jTextField1");

        mrn.setText("jTextField1");

        hbn.setText("jTextField1");

        bn.setText("jTextField1");

        cn.setText("jTextField1");

        vpn.setText("jTextField1");

        ln.setText("jTextField1");

        ipa.setText("jTextField1");

        ui.setText("jTextField1");

        ea.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16)
                            .addComponent(jLabel25)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel3))
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addGap(287, 287, 287)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabelea)
                        .addComponent(jLabelui)
                        .addComponent(jLabelpa)
                        .addComponent(jLabelln)
                        .addComponent(jLabelpn)
                        .addComponent(jLabelcn)
                        .addComponent(jLabelbs)
                        .addComponent(jLabelhbn)
                        .addComponent(jLabelM)
                        .addComponent(jLabelssn)
                        .addComponent(jLabelF)
                        .addComponent(jLabelTN)
                        .addComponent(jLabelG)
                        .addComponent(jLableN))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(32, 32, 32))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLableN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jLabelG)
                    .addGap(26, 26, 26)
                    .addComponent(jLabelTN)
                    .addGap(52, 52, 52)
                    .addComponent(jLabelF)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelssn)
                    .addGap(113, 113, 113)
                    .addComponent(jLabelM)
                    .addGap(4, 4, 4)
                    .addComponent(jLabelhbn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelbs)
                    .addGap(66, 66, 66)
                    .addComponent(jLabelcn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelpn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelln)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabelui)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabelea))))
                        .addComponent(jLabelpa))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bn;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField ea;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField gd;
    private javax.swing.JTextField hbn;
    private javax.swing.JTextField ipa;
    private javax.swing.JTextField jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelG;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelTN;
    private javax.swing.JLabel jLabelbs;
    private javax.swing.JLabel jLabelcn;
    private javax.swing.JLabel jLabelea;
    private javax.swing.JLabel jLabelhbn;
    private javax.swing.JLabel jLabelln;
    private javax.swing.JLabel jLabelpa;
    private javax.swing.JLabel jLabelpn;
    private javax.swing.JLabel jLabelssn;
    private javax.swing.JLabel jLabelui;
    private javax.swing.JLabel jLableN;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mrn;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField ui;
    private javax.swing.JTextField vpn;
    // End of variables declaration//GEN-END:variables

    private void viewUser() {
        name.setText(user.getName());
        gd.setText(user.getGeographicData());
        String telno = String.valueOf(user.getTelephoneNumber());
        tn.setText(telno);
        //user.setDateOfBirth(JFileChooser.getDefaultLocale());
        String faxno = String.valueOf(user.getFaxNumber());
        fn.setText(faxno);
        ea.setText(user.getEmailAddress());
        String ssnum = String.valueOf(user.getSsn());
        ssn.setText(ssnum);
        mrn.setText(user.getMedicalRecordNumber());
        hbn.setText(user.getHealthPlanBeneficiary());
        String banu = String.valueOf(user.getBankAccountNumbers());
        bn.setText(banu);
        String cnum = String.valueOf(user.getLicenseNumber());
        cn.setText(cnum);
        vpn.setText(user.getLicensePlates());
        ln.setText(user.getLinkedIn());
        String uid = String.valueOf(user.getUniqueIdentifier());
        ui.setText(uid);
        ipa.setText(user.getInternetProtocolAddress());
        String dob = String.valueOf(user.getDateOfBirth());
        jDateChooser1.setText(dob);
        jLabelImage.setIcon(user.getImage());
    }
}
